# Generated by Django 4.1 on 2022-08-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('relacion', models.CharField(max_length=140)),
                ('cantidad_de_hijos', models.IntegerField()),
            ],
        ),
    ]
